version: 1.0.{build}-auto
pull_requests:
  do_not_increment_build_number: true
configuration: Release
init:
- cmd: >-
    set PATH=%PATH%;%PYTHON%/Scripts/

    pip.exe install --upgrade pip --user

    pip.exe install urllib3==1.25.11

    pip.exe install conan

    conan user
before_build:
  matrix:
    - cmd: cmake -DCMAKE_BUILD_TYPE=Release . -DDEBUG=On
    - cmd: cmake -DCMAKE_BUILD_TYPE=Release . -DDEBUG=Off
build:
  project: linda-lib.sln
  parallel: true
  verbosity: minimal
artifacts:
  matrix:
    - path: x64\Release\linda-lib.dll
    name: linda_lib_release
    - path: x64\Debug\linda-lib.dll
    name: linda_lib_debug
deploy:
- provider: GitHub
  auth_token:
    secure: PvMCuQd7iHDAzxJHSch9s45Pe7M/nJRuqvP5DXCo/mWuCc/HuHuZC2Fpngu3lJ4B
  matrix:
    artifact: linda_lib_release
    artifact: linda_lib_debug
  draft: false